// MQ0 Tiled Extension - AI Review (Phase 3.2).
// Tiled itself NEVER calls an external AI API (its scripting sandbox has no network
// access, and this extension is not the place for API keys anyway).
//   - runMockReview() is UNCHANGED behavior from Phase 2 (kept exactly as-is per "Mock Modeを残す").
//   - runReview() is what the "AI Review" button (in the "MQ0 Tools..." dialog under the
//     Map menu) calls. In "mock" aiMode it just calls runMockReview(). In "real" aiMode it
//     looks for a JSON result that was already generated by
//     `node tools/mq0-map-ai/review-map.js --provider real` (Config.aiReview.resultsDir)
//     and displays it. If none exists (or it can't be read), it WARNs and falls back to Mock.
import Config from "./config.mjs";
import Validator from "./validator.mjs";
import ReviewPackage from "./review-package.mjs";
import Requirements from "./requirements.mjs";

const FUTURE_CHECKS = [
    "MQ0 map requirements",
    "map scale",
    "movement distance",
    "NPC density",
    "event placement",
    "item validity",
    "story flow",
    "reference image consistency"
];

function runMockReview() {
    var map = Validator.getActiveMap();
    var built = ReviewPackage.buildReviewPackage(map);
    var pkg = built.package;

    var lines = [];
    if (!pkg.map) {
        lines.push({ level: "FAIL", message: "開いているマップがありません。" });
    } else {
        lines.push({ level: "PASS", message: "Map data successfully loaded." });
        lines.push({ level: "INFO", message: "AI connection is not enabled yet." });
    }

    return { package: pkg, lines: lines, summary: buildMockSummary(pkg, lines) };
}

function buildMockSummary(pkg, lines) {
    var out = ["MQ0 AI Review", "Mode: MOCK", ""];

    out.push("Map");
    out.push("  " + (pkg.map ? (pkg.map.id || "(no id)") + " / " + (pkg.map.name || "(no name)") : "(開いているマップがありません)"));

    out.push("Requirements");
    if (pkg.requirements.selected.length > 0) {
        pkg.requirements.selected.forEach(function (r) { out.push("  " + r.path); });
    } else {
        out.push("  (none selected)");
    }

    out.push("Reference");
    if (pkg.reference.configured) {
        out.push("  " + pkg.reference.path);
    } else if (pkg.reference.layer) {
        out.push("  layer present, no image set (" + pkg.reference.layer + ")");
    } else {
        out.push("  not configured");
    }

    out.push("Validation");
    if (pkg.validation.errors.length === 0 && pkg.validation.warnings.length === 0) {
        out.push("  PASS  Future AI input package is ready.");
    } else {
        out.push("  " + pkg.validation.errors.length + " errors, " + pkg.validation.warnings.length + " warnings");
    }

    out.push("");
    out.push("Review:");
    for (var i = 0; i < lines.length; i++) out.push(lines[i].level + "  " + lines[i].message);

    out.push("");
    out.push("SUGGESTION  Future AI Review will inspect:");
    for (var j = 0; j < FUTURE_CHECKS.length; j++) {
        out.push("  - " + FUTURE_CHECKS[j]);
    }

    out.push("");
    out.push("(Real AI Review: run `node tools/mq0-map-ai/review-map.js --map <path> --provider real` then switch Config.aiMode to \"real\".)");
    out.push("(Use the \"Build Review Package\" button in MQ0 Tools... (Map menu) to preview/export the full JSON package this is based on.)");

    return out.join("\n");
}

// tools/mq0-map-ai/review-map.js が書き出した ai-review.json を読む(存在すれば)。
// TextFile読み込みAPIが無い/失敗する場合はnullを返し、呼び出し側でMockへフォールバックする。
function loadCachedRealResult(map) {
    try {
        if (typeof File === "undefined" || typeof File.exists !== "function" || typeof TextFile === "undefined") return null;
        var root = Requirements.resolveRepoRoot();
        if (!root) return null;

        var props = (Validator.buildSnapshot(map) || {}).properties || {};
        var folder = ReviewPackage.outputFolderNameFor(props, map && map.fileName);
        var filePath = root + "/" + Config.aiReview.resultsDir + "/" + folder + "/ai-review.json";
        if (!File.exists(filePath)) return null;

        var f = new TextFile(filePath, TextFile.ReadOnly);
        var content = typeof f.readAll === "function" ? f.readAll() : "";
        if (typeof f.close === "function") f.close();
        return JSON.parse(content);
    } catch (e) {
        return null;
    }
}

function severityRank(sev) {
    var order = { ERROR: 0, WARN: 1, INFO: 2, SUGGESTION: 3 };
    return order[sev] !== undefined ? order[sev] : 9;
}

// AI Review Result JSON(§3 Schema)を、Tiled上の表示テキストへ整形する。
function buildRealSummary(result) {
    var out = ["MQ0 AI Review", ""];
    out.push("Map");
    out.push("  " + (result.map ? (result.map.id || "(no id)") + " / " + (result.map.name || "(no name)") : "(unknown)"));
    out.push("Mode");
    out.push("  REAL (" + (result.provider || "unknown") + ", cached " + (result.generatedAt || "?") + ")");
    out.push("Summary");
    out.push("  " + (result.summary || "(no summary)"));

    var issues = (result.issues || []).slice().sort(function (a, b) { return severityRank(a.severity) - severityRank(b.severity); });
    issues.forEach(function (issue) {
        out.push("");
        out.push(issue.severity + "  " + issue.message);
        if (issue.evidence && issue.evidence.length > 0) {
            out.push("Evidence");
            issue.evidence.forEach(function (e) { out.push("  " + (e.source || "?") + (e.section ? " (" + e.section + ")" : "")); });
        }
        if (issue.suggestion) {
            out.push("Suggestion");
            out.push("  " + issue.suggestion);
        }
        if (typeof issue.confidence === "number") {
            out.push("Confidence");
            out.push("  " + Math.round(issue.confidence * 100) + "%");
        }
    });

    if ((result.suggestions || []).length > 0) {
        out.push("");
        out.push("Additional Suggestions:");
        result.suggestions.forEach(function (s) { out.push("  - " + s.description + (s.reason ? " (" + s.reason + ")" : "")); });
    }

    if ((result.limitations || []).length > 0) {
        out.push("");
        out.push("Limitations:");
        result.limitations.forEach(function (l) { out.push("  - " + l); });
    }

    out.push("");
    out.push("(This does not change the Tiled map. Apply any accepted suggestion yourself in Tiled.)");
    return out.join("\n");
}

// "AI Review" ボタン(MQ0 Tools...ダイアログ内)の本体。Config.aiModeに応じてMock or キャッシュ済みReal結果を返す。
function runReview() {
    var map = Validator.getActiveMap();

    if (Config.aiMode === "real") {
        var cached = loadCachedRealResult(map);
        if (cached) {
            return { mode: "real", result: cached, summary: buildRealSummary(cached) };
        }
        var mock = runMockReview();
        var warnedSummary = [
            "MQ0 AI Review",
            "Mode: REAL (結果が見つからないためMockへフォールバック)",
            "",
            "実AI Reviewの結果が見つかりません。先に以下を実行してください:",
            "  node tools/mq0-map-ai/review-map.js --map <このマップの.tmjパス> --provider real",
            "",
            "----- 以下はMock AI Review -----",
            mock.summary
        ].join("\n");
        return { mode: "mock-fallback", result: mock.package, summary: warnedSummary };
    }

    var mockResult = runMockReview();
    return { mode: "mock", result: mockResult.package, summary: mockResult.summary };
}

const MQ0AIReview = {
    runMockReview: runMockReview,
    runReview: runReview
};

export default MQ0AIReview;
